[package]
name = "redis-proto"
version = "0.1.0"
edition = "2021"

[lib]
name = "redis_proto"
path = "src/lib.rs"

[[bin]]
name = "redis-proto"
path = "src/main.rs"

[dependencies]
sloggers = "0.3.4"
lazy_static = "1.4.0"
slog = "2.5.2"